name: release

on:
  push:
    tags:
      - 'v[0-9]+.*'

permissions:
  contents: write

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
      
      - name: 🛒 Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1
          path: bungee
      
      - name: 🛠️ Configure, build and install presets
        env:
          GITHUB_REF_NAME: ${{github.ref_name}}
          CMAKE_BUILD_PARALLEL_LEVEL: 2
          ANDROID_NDK: /usr/local/lib/android/sdk/ndk/26.3.11579264
        run: |
          sudo apt-get -y install mingw-w64
          for PRESET in \
            windows-x86_64 \
            ; do
            cmake \
              --preset ${PRESET} \
              -S ${{github.workspace}}/bungee \
              -B ${{github.workspace}}/builds/${PRESET} \
              -D CMAKE_INSTALL_PREFIX=${{github.workspace}}/install/bungee-${PRESET} \
              -D BUNGEE_VERSION=${GITHUB_REF_NAME//v}  \
              -G "Unix Makefiles"
            cmake \
              --build ${{github.workspace}}/builds/${PRESET} \
              --target install
            touch ${{github.workspace}}/install/bungee-${PRESET}/${{github.ref_name}}
          done

      - name: 🗜️ Prepare archives
        run: |
          mkdir ${{github.workspace}}/artifact
          cd ${{github.workspace}}/install/bungee-windows-x86_64
          zip -r ${{github.workspace}}/artifact/bungee-${{github.ref_name}}-windows.zip *

      - name: ✈️ Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-latest-install 
          path: ${{github.workspace}}/artifact

          
  build_macos:
    runs-on: macos-latest
    needs: build_ubuntu
    steps:
      
      - name: 🛒 Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1
          path: bungee

      - name: 🪂 Download artifact that was built un Ubuntu
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-latest-install 
          path: ${{github.workspace}}/artifact

      - name: 🛠️ Configure, build and install Apple presets
        env:
          GITHUB_REF_NAME: ${{github.ref_name}}
          CMAKE_BUILD_PARALLEL_LEVEL: 2
        run: |
          for PRESET in \
            apple-mac \
            ; do
            cmake \
              --preset ${PRESET} \
              -S bungee \
              -B builds/${PRESET} \
              -D CMAKE_INSTALL_PREFIX=${{github.workspace}}/install/${PRESET} \
              -D BUNGEE_VERSION=${GITHUB_REF_NAME//v}
            cmake \
              --build builds/${PRESET} \
              --config Release
            cmake \
              --install builds/${PRESET}
          done

      - name: 🗜️ Prepare archives
        run: |
          tar -cvzf ${{github.workspace}}/artifact/bungee-${{github.ref_name}}-mac.tgz ${{github.workspace}}/install/apple-mac/*

      - name: ⭐ Create release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          gh release create "${{github.ref_name}}" \
              --repo="${{github.repository}}" \
              --title="Bungee ${{github.ref_name}}" \
              ${{github.workspace}}/artifact/*
  