name: release

on:
  push:
    tags:
      - 'v[0-9]+.*'

permissions:
  contents: write

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
      
      - name: 🛒 Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1
          path: bungee
      
      - name: 🛠️ Configure, build and install presets
        env:
          GITHUB_REF: ${{github.ref}}
          CMAKE_BUILD_PARALLEL_LEVEL: 2
          ANDROID_NDK: /usr/local/lib/android/sdk/ndk/26.3.11579264
        run: |
          sudo apt-get -y install mingw-w64
          for PRESET in \
            linux-x86_64 \
            windows-x86_64 \
            android-armeabi-v7a \
            android-arm64-v8a \
            android-x86 \
            android-x86_64 \
            ; do
            BUNGEE_VERSION=${GITHUB_REF//v} \
            cmake \
              --preset ${PRESET} \
              -S ${{github.workspace}}/bungee \
              -B ${{github.workspace}}/builds/${PRESET} \
              -D CMAKE_INSTALL_PREFIX=${{github.workspace}}/ubuntu/ \
              -D BUNGEE_ABI_NAME=${PRESET} \
              -D BUNGEE_VERSION=${BUNGEE_VERSION} \
              -G "Unix Makefiles"
            cmake \
              --build ${{github.workspace}}/builds/${PRESET}/ \
              --target install 
          done
      
      - name: ✈️ Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-latest-install 
          path: ${{github.workspace}}/ubuntu/
          
  build_macos:
    runs-on: macos-latest
    needs: build_ubuntu
    steps:
      
      - name: 🛒 Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1
          path: bungee

      - name: 🪂 Download artifact that was built un Ubuntu
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-latest-install 
          path: ${{github.workspace}}/bungee-${{ github.ref_name }}

      - name: 🛠️ Configure, build and install Apple presets
        env:
          GITHUB_REF: ${{github.ref}}
          CMAKE_BUILD_PARALLEL_LEVEL: 2
        run: |
          for PRESET in \
            apple-mac-arm64  \
            apple-mac-x86_64  \
            apple-ios-arm64  \
            apple-ios-x86_64  \
            ; do
            BUNGEE_VERSION=${GITHUB_REF//v} \
            cmake \
              --preset ${PRESET} \
              -S ${{github.workspace}}/bungee \
              -B ${{github.workspace}}/builds/${PRESET} \
              -D CMAKE_INSTALL_PREFIX=${{github.workspace}}/bungee-${{ github.ref_name }} \
              -D BUNGEE_ABI_NAME=${PRESET} \
              -D BUNGEE_VERSION=${BUNGEE_VERSION}
            cmake \
              --build ${{github.workspace}}/builds/${PRESET} \
              --config Release
            cmake \
              --install ${{github.workspace}}/builds/${PRESET}
          done

      - name: 🗜️ Prepare archive
        run: |
          tar -cvzf ${{github.workspace}}/bungee-${{ github.ref_name }}.tgz -C ${{github.workspace}} bungee-${{ github.ref_name }}

      - name: ⭐ Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ github.ref_name }}" \
              --repo="${{ github.repository }}" \
              --title="Bungee ${{ github.ref_name }}" \
              ${{github.workspace}}/bungee-${{ github.ref_name }}.tgz
